# Generated by Django 5.0.6 on 2024-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('text', models.TextField(verbose_name='текст')),
                ('minimum_expected_weight', models.IntegerField(blank=True, null=True)),
                ('maximum_expected_weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'db_table': 'Recommendation',
            },
        ),
    ]
