# Generated by Django 5.0.6 on 2024-06-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='maximum_expected_weight',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='minimum_expected_weight',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='for_current_max_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный текущий вес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='for_current_min_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный текущий вес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='max_expected_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный желаемый вес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='min_expected_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный желаемый вес'),
        ),
    ]
