# Generated by Django 5.0.6 on 2024-06-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_remove_recommendation_maximum_expected_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='name',
        ),
    ]
