# Generated by Django 5.0.6 on 2024-06-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_remove_recommendation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
